#pragma once

#include "rvi_base.h"

enum class COMMAND_HEADER
{
	NOP = 0,
	REQUEST_ACK = 1,
	RESPONSE_ACK = 2,
	DRAW_LINE = 3,
	SELECT_FRAME = 4,
	DELETE_FRAME = 5,
	SET_FRAME_COLOR = 6,
	SET_FRAME_TRANSFORM = 7,
	SET_FRAME_OFFSET = 8,
	SET_FRAME_SCALE = 9,
	SET_FRAME_ROTATION = 10,
	CLEAR_FRAME = 11,
	CREATE_DEFINITION = 12,
	DELETE_DEFINITION = 13
};